Minions:
  # 矿工(Type)
  Miner:

    # 允许获取物品的设置
    Item:
      # 物品名称标准在这里查：https://bukkit.windit.net/javadoc/org/bukkit/Material.html
      # 获取原石的权重是 0.3
      COBBLESTONE: 30
      DIAMOND: 30
      COAL: 30

    # 工人升级设置
    Upgrade:

      # 工人效率设置
      Amount:

        # 升级工人效率需要花费 500 金币
        Cost: 500

        # 每升级一次 10 分钟多获取 100 个方块
        Upgrade: 100

      # 工人背包配置
      Size:

        # 升级工人背包需要花费 500 金币
        Cost: 500

        # 每次升级增加 3 行箱子
        Upgrade: 3
    # 工人的描述（出现在物品形式工人的lore里）
    Describe: "一个苦逼工人"
    # 物品形式的工人的皮肤
    SkullTexture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTg3Y2ZjY2U2NzI0Y2Y3MzgyZDZjNjUyMzJjZDY2Njk2ZDQyNjQ2MWM4MjE2MWE3OGYyMjI0Y2EyM2MzMWMifX19"

  # 物品形式的工人配置
MinionItem:
    Name: "&a樱花镇の&6%Type%"
    Lore: ##请确保不会出现其他数字/每行只能有一个参数
        - '&d%Describe%'
        - '&e容量:&c%Size%'
        - '&e效率:&c%Amount%'
Message:
  NoMinions: 你还没有工人

## 工人背包菜单
Menu:
  ## 样式，Top 为顶部 Bottom 为底部 菜单一共占9个格子只有翻页按钮和占位符
  Style: Bottom
  ## Slot是9个按钮的配置 从左往右由1开始 LastPage(上一页)、NextPage(下一页)、PlaceHolder(无实际功能，仅占位)
  ## 支持自定义菜单按钮格式如LastPage 类型随意。Slot总数必须小于9
  # mybutton:
  #    Material: GLISTERING_MELON_SLICE
  #    Name: "§d我的按钮"
  #    Slots: 6,7
  LastPage:
    Material: GLISTERING_MELON_SLICE
    Name: "§d上一页"
    Slots: 1,2,3,4
  PlaceHolder:
    Material: LIGHT_BLUE_STAINED_GLASS_PANE
    Name: " "
    Slots: 5
  NextPage:
    Material: GLISTERING_MELON_SLICE
    Name: "§d下一页"
    Slots: 6,7,8,9
  LockArea:
    Material: RED_STAINED_GLASS_PANE
    Name: "§d待解锁"



