MinionItem:
    Name: "&a樱花镇の&6%Type%"
    Lore: # 请确保不会出现其他数字/每行只能有一个参数
        - '&d%Describe%'
        - '&e容量:&c%Size%'
        - '&e效率:&c%Amount%'

# 工人每次收集时间
CollectTime: 1

Message:
  NoMinions: 你还没有工人



