Minions:
  # 矿工
  Miner:

    # 允许获取物品的设置
    Item:

      # 获取原石的权重是 0.3
      COBBLESTONE: 50
      DIAMOND: 40
      COAL: 10

    # 工人升级设置
    Upgrade:

      # 工人效率设置
      Amount:

        # 升级工人效率需要花费 500 金币
        Cost: 500

        # 每升级一次 10 分钟多获取 100 个方块
        Upgrade: 100

      # 工人背包配置
      Size:

        # 升级工人背包需要花费 500 金币
        Cost: 500

        # 每次升级增加 3 行箱子
        Upgrade: 3

Message:
  NoMinions: 你还没有工人